# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=200)),
                ('item_text', models.TextField()),
                ('item_date', models.DateTimeField()),
                ('item_likes', models.IntegerField()),
            ],
            options={
                'db_table': 'shop',
            },
        ),
    ]
