# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, verbose_name='Name of the category')),
                ('category_alias', models.SlugField(verbose_name='Category alias')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_likes',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_text',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_title',
        ),
        migrations.AddField(
            model_name='item',
            name='item_alias',
            field=models.SlugField(default=0, verbose_name='Item alias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default=0, max_length=255, verbose_name='Image link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(default=0, max_length=200, verbose_name='Name of the item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
        migrations.AlterModelTable(
            name='item',
            table=None,
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.Category'),
            preserve_default=False,
        ),
    ]
