# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20161109_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_alias',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_alias',
        ),
        migrations.AddField(
            model_name='category',
            name='category_text',
            field=models.TextField(default='Input the description here', verbose_name='Category description'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_text',
            field=models.TextField(default='Input the description here', verbose_name='Item description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=200, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=200, verbose_name='Item name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.IntegerField(default=0, verbose_name='Item price'),
        ),
    ]
